version: 2

models:

  - name: agg_trip_stats_daily
    description: Daily roll-up of Citibike trip stats

    columns:
      - name: date_stamp
        description: Date for daily rollup based on trip start time