version: 2

models:

  - name: trip_stats_daily
    description: Daily roll-up of Citibike trip stats

    columns:
      - name: date_stamp
        description: Date
        tests:
          - not_null
          - unique
